exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments

title : Nestico Architect Inc.
tagline: Consultation You Can Build On!

production_url : http://nesticoarchitect.on.ca

permalink: pretty
relative_permalinks: true
